BEGIN;

DROP TABLE IF EXISTS figurinhas_repetidas CASCADE;
DROP TABLE IF EXISTS figurinhas_coladas CASCADE;
DROP TABLE IF EXISTS figurinhas CASCADE;
DROP TABLE IF EXISTS jogadores CASCADE;
DROP TABLE IF EXISTS selecoes CASCADE;
DROP TABLE IF EXISTS grupos CASCADE;

DROP TABLE IF EXISTS album_duplicate_stickers CASCADE;
DROP TABLE IF EXISTS album_stickers CASCADE;
DROP TABLE IF EXISTS album_teams CASCADE;
DROP TABLE IF EXISTS album_groups CASCADE;

COMMIT;
